# Generated by Django 5.2 on 2025-06-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medvaultapp', '0002_alter_qrcode_qr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='qr_image',
            field=models.ImageField(blank=True, upload_to='qr_codes/'),
        ),
    ]
