# Generated by Django 5.2 on 2025-06-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medvaultapp', '0005_wallet_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='wallet_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
