# Generated by Django 5.2 on 2025-06-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medvaultapp', '0006_wallet_wallet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_name',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
