# Generated by Django 5.2 on 2025-06-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medvaultapp', '0007_alter_wallet_wallet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='user_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
