# Generated by Django 5.2 on 2025-06-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medvaultapp', '0010_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
