# Generated by Django 5.2 on 2025-06-30 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medvaultapp', '0012_customuser_is_verified_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verification_token',
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
