# Generated by Django 5.2 on 2025-07-06 20:14

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medvaultapp', '0014_hospitalprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_hospital',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('specification', models.JSONField(help_text='Seperate by Comma')),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_registration_num', models.CharField(max_length=300)),
                ('hospital_document', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='hospital_document')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
            },
        ),
        migrations.DeleteModel(
            name='HospitalProfile',
        ),
    ]
