# Generated by Django 5.2 on 2025-07-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medvaultapp', '0017_hospital_created_at_hospital_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
