# Generated by Django 5.2 on 2025-07-09 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medvaultapp', '0018_qrcode_activated_at_qrcode_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='activated_at',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='is_active',
        ),
    ]
