# Generated by Django 5.2 on 2025-07-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medvaultapp', '0019_remove_qrcode_activated_at_remove_qrcode_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
